"""Build the site's Wuzuan Ink core subsets (SIL OFL 1.1).

This is a custom derivative of LXGW WenKai TC, not a claim of original CJK
letter skeletons. Every glyph receives the same outline treatment. Both weights
retain the upstream character repertoire. The current site's characters get a
small core subset; --full also builds the complete family in web subsets.
"""
import argparse
from pathlib import Path
from copy import deepcopy
import hashlib
import html
import json
import math
import re
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.ttLib.tables._g_l_y_f import Glyph, GlyphCoordinates
from fontTools.pens.svgPathPen import SVGPathPen

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'scripts/font-sources'
OUT = ROOT / 'public/fonts/ink'
OUT.mkdir(parents=True, exist_ok=True)
FAMILY = 'Wuzuan Ink'
REVISION = '2'

def site_characters():
    content = ''
    for folder, pattern in [('views', '*.ejs'), ('public/js', '*.js'), ('public/js', '*.mjs')]:
        for path in (ROOT / folder).rglob(pattern):
            content += html.unescape(path.read_text(encoding='utf-8'))
    for filename in ['server.js', 'build.js', 'public/css/style.css']:
        content += html.unescape((ROOT / filename).read_text(encoding='utf-8'))
    # All printable ASCII, punctuation, and the actual CJK content/dynamic labels.
    return set(range(32, 127)) | {ord(c) for c in content if ord(c) >= 160}

def ranges(points):
    groups=[]
    for code in sorted(points):
        if groups and code == groups[-1][1]+1:
            groups[-1][1]=code
        else:
            groups.append([code,code])
    return ','.join(f'U+{a:X}' if a==b else f'U+{a:X}-{b:X}' for a,b in groups)

def customize(font):
    glyf=font['glyf']
    drawn={}
    for index,name in enumerate(font.getGlyphOrder()):
        coords, endpoints, flags = glyf[name].getCoordinates(glyf)
        glyph = Glyph()
        if not coords:
            glyph.numberOfContours=0
        else:
            # A controlled forward lean, compact body and a shallow rising pen
            # arc. Applied to real outlines, including composite glyphs.
            advance=font['hmtx'][name][0]
            phase=(sum(map(ord,name)) % 7 - 3)*.45
            points=[]
            for x,y in coords:
                nx=advance/2 + (x-advance/2)*.94 + (y-350)*.065
                nx+=4*math.sin((y+80)*math.pi/1000)
                ny=y*.98 + 6*math.sin(x*math.pi/1000) + phase
                points.append((round(nx),round(ny)))
            glyph.numberOfContours=len(endpoints)
            glyph.coordinates=GlyphCoordinates(points)
            glyph.endPtsOfContours=endpoints
            glyph.flags=flags
        drawn[name]=glyph
    for name,glyph in drawn.items():
        glyf[name]=glyph
        glyph.recalcBounds(glyf)
        advance,_=font['hmtx'][name]
        font['hmtx'][name]=(advance,getattr(glyph,'xMin',0))
    weight=font['OS/2'].usWeightClass
    style='Bold' if weight >= 600 else 'Regular'
    # Keep upstream copyright and license records. Rename all family identifiers.
    replacements={1:FAMILY,2:style,3:f'WuzuanInk-{style}-1.000',
                  4:f'{FAMILY} {style}',5:'Version 1.000',
                  6:f'WuzuanInk-{style}',16:FAMILY,17:style,
                  10:'Custom outline derivative of LXGW WenKai TC. SIL OFL 1.1. '
                     'Narrowed glyph body, forward pen angle, rising contour arc.'}
    font['name'].names=[n for n in font['name'].names if n.nameID not in replacements]
    for name_id,value in replacements.items():
        font['name'].setName(value,name_id,3,1,0x409)
    font['head'].created=font['head'].modified=3862400000
    font.recalcTimestamp=False
    # Fixed horizontal metrics remain available for dynamic time/date displays.
    return font

def save_subset(font,points,filename):
    copy=deepcopy(font)
    options=subset.Options()
    options.hinting=False
    options.drop_tables += ['meta']
    options.name_IDs=['*']
    options.name_legacy=True
    options.name_languages=['*']
    subsetter=subset.Subsetter(options=options)
    subsetter.populate(unicodes=points)
    subsetter.subset(copy)
    copy.flavor='woff2'
    copy.save(OUT/filename)

def export_wordmark(font,text,filename):
    glyphset=font.getGlyphSet()
    cmap=font.getBestCmap()
    paths=[]; cursor=30
    for char in text:
        name=cmap[ord(char)]
        pen=SVGPathPen(glyphset)
        glyphset[name].draw(pen)
        paths.append(f'<path transform="translate({cursor},1040) scale(1,-1)" d="{pen.getCommands()}"/>')
        cursor+=font['hmtx'][name][0]
    svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {cursor+30} 1340" fill="#e0e0e0"><title>{text}</title>{"".join(paths)}</svg>'
    (ROOT/'public/images/identity'/filename).write_text(svg,encoding='utf-8')

def main(full=False):
    core_css=['/* Generated by scripts/build-ink-fonts.py. Site characters. */']
    css=['/* Generated by scripts/build-ink-fonts.py. Extended repertoire. */']
    manifest={'family':FAMILY,'license':'../OFL.txt','source':'LXGW WenKai TC',
              'sourceUrl':'https://github.com/lxgw/LxgwWenkaiTC','sources':{},'files':[]}
    required=site_characters()
    reference=None
    for style,weight in [('Regular',400),('Bold',700)]:
        source=SOURCE/f'LXGWWenKaiTC-{style}.ttf'
        manifest['sources'][style]={'sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
            'url':f'https://raw.githubusercontent.com/google/fonts/main/ofl/lxgwwenkaitc/{source.name}'}
        font=customize(TTFont(source))
        supported=set(font.getBestCmap())
        if reference is not None:
            assert supported==reference,'Weights must cover the same characters'
        reference=supported
        core=required & supported
        chunks=[('core',core)]
        if full:
            remainder=sorted(supported-core)
            chunks += [(f'extended-{i//1024:02}',set(remainder[i:i+1024])) for i in range(0,len(remainder),1024)]
        print(f'{style}: {len(supported)} characters; {len(core)} in core.',flush=True)
        for label,points in chunks:
            filename=f'wuzuan-ink-{weight}-{label}-v{REVISION}.woff2'
            save_subset(font,points,filename)
            (core_css if label == 'core' else css).append('@font-face {\n'+f"    font-family: '{FAMILY}';\n    font-style: normal;\n    font-weight: {weight};\n"
                       +f"    font-display: swap;\n    src: url('/fonts/ink/{filename}') format('woff2');\n"
                       +f'    unicode-range: {ranges(points)};\n'+'}')
            manifest['files'].append({'file':filename,'weight':weight,'codepoints':sorted(points),'bytes':(OUT/filename).stat().st_size})
        if weight==700:
            export_wordmark(font,'Wuzuan','wuzuan-wordmark.svg')
            export_wordmark(font,'吳鑽','wuzuan-name.svg')
    manifest['codepoints']=sorted(reference)
    (ROOT/'public/css/ink-fonts-core.css').write_text('\n\n'.join(core_css)+'\n',encoding='utf-8')
    if full:
        (OUT/'coverage.json').write_text(json.dumps(manifest,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
        (ROOT/'public/css/ink-fonts.css').write_text('\n\n'.join(css)+'\n',encoding='utf-8')
    print(f"Done: {len(manifest['files'])} WOFF2 files, {sum(f['bytes'] for f in manifest['files']):,} bytes total.",flush=True)

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--full',action='store_true',help='also regenerate extended subsets and coverage manifest')
    main(parser.parse_args().full)
